events {}

http {
  server {
    listen 8080;
    server_name _;

    error_page 403 /error403.html;

    location = /edge403 {
      return 403;
    }

    location = /error403.html {
      root /usr/share/nginx/html;
      internal;
    }

    location /proxy/spring-pass {
      proxy_pass http://springlike:8080/;
      proxy_set_header Host $host;
    }

    location /proxy/spring-intercept {
      proxy_intercept_errors on;
      proxy_pass http://springlike:8080/;
      proxy_set_header Host $host;
    }

    location /proxy/tomcat-pass {
      proxy_pass http://tomcatlike:8080/;
      proxy_set_header Host $host;
    }

    location /proxy/tomcat-intercept {
      proxy_intercept_errors on;
      proxy_pass http://tomcatlike:8080/;
      proxy_set_header Host $host;
    }

    location /proxy/appjson-pass {
      proxy_pass http://appjson:8080/;
      proxy_set_header Host $host;
    }
  }
}
