events {}

http {
  server {
    listen 8080 default_server;
    server_name _;

    error_page 403 /error403.html;

    location = /__lab/front403 {
      return 403;
    }

    location = /__lab/front400 {
      default_type text/html;
      return 400 "Not Found(400)";
    }

    location = /error403.html {
      root /usr/share/nginx/html;
      internal;
    }

    location = /auth/ {
      proxy_pass http://sample-next:8080;
      proxy_set_header Host $host;
    }

    location = /gold-platform/register-password/ {
      proxy_pass http://sample-next:8080;
      proxy_set_header Host $host;
    }

    location / {
      default_type text/plain;
      return 404;
    }
  }

  server {
    listen 8080;
    server_name www.example-target.local;

    location = /notice.do {
      proxy_pass http://sample-web:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Test $http_x_test;
    }
  }

  server {
    listen 8080;
    server_name auth.example-target.local;

    location = /__lab/upgrade101 {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
      proxy_pass http://sample-next:8080;
    }

    location = /auth/ {
      proxy_pass http://sample-next:8080;
      proxy_set_header Host $host;
    }

    location = /gold-platform/register-password/ {
      proxy_pass http://sample-next:8080;
      proxy_set_header Host $host;
    }
  }

  server {
    listen 27000;
    server_name api.example-target.local;

    location = /swapp/sw5/5667 {
      proxy_pass http://sample-appjson:8080;
      proxy_set_header Host $host;
      proxy_set_header Content-Type $content_type;
    }
  }

  server {
    listen 8080;
    server_name static.example-target.local;

    location = /static/v2/publishing/sample_assets/css/style_pc.css {
      root /usr/share/nginx/html;
      add_header Cache-Control "max-age=2592000";
      add_header X-Cache-Status "HIT";
      default_type text/css;
      try_files /style_pc.css =404;
    }
  }
}
